#配置文件版本号
Version: 1.1

#更新时间(单位: Tick)
UpdateTime: 10
#关闭记分板的世界
DisableWorld:
- WorldName
#记分板
Boards:
  #默认记分板
  default:
    #记分板顺序(将按照从小到大依次检测 比如 1-50 优先检测 1 符合则显示 不符合 检测 2 ...)
    index: 50
    #显示时间(格式为yyyy-MM-dd HH:mm:ss)
    time: 
      start: '2016-01-01 00:00:00'
      end: '2020-01-01 00:00:00'
    #记分板标题
    title: '喵式记分板简介'
    #记分板权限
    permission: mb.default
    #记分板内容
    #注意 不得超过38个字符 包括颜色字符 超过部分自动截取
    #注意 不得超过15行 超出部分 自动忽略
    lines:
    - '&6插件名称: &a%plugin_name%'
    - '&7------------------------------'
    - '&6插件版本: &b%plugin_version%'
    - '&7------------------------------'
    - '&6插件作者: &c%plugin_author%'
    - '&7------------------------------'
    - '&6玩家名称: &a%player_displayname%'
    - '&7------------------------------'
    - '&6您所在的位置: &b%player_world% &a%player_x%,%player_y%,%player_z%'
    - '&7------------------------------'
    - '&6您所在的角度: &bYaw &a%player_yaw% &bPitch &a%player_pitch%'
    - '&7------------------------------'
    - '&6服务器使用内存: &a%server_ram_used%/%server_ram_total%'
    - '&7------------------------------'
    - '&6离2017年还剩: &a%time_left_2017-01-01`00:00:00%秒'